name: riverpod_testing
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  flutter_svg: ^2.1.0

  # Riverpod
  hooks_riverpod: ^3.0.0-dev.16

  # Database
  riverpod_sqflite: ^0.1.2

  # Annotation Packages
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^3.0.0-dev.16

  # Utils
  path_provider: ^2.1.5
  uuid: ^4.5.1

  # Router
  go_router: ^16.0.0

  fpdart: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0-dev.16
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/